name: Build and Release

on:
  push:
    branches:
      - "release/v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Install system-wide LibSodium
        run: sudo apt-get install -y libsodium-dev

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Initialize submodule, generate jars, and build (including tests)
        run: chmod +x initialize.sh && ./initialize.sh

      - name: Get branch name
        id: get_branch
        run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/release/v}

      - name: Run Semantic Release and Update gradle.properties version
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
