name: Generate Release

on:
  push:
    branches:
      - "release/*"

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Install system-wide LibSodium
        run: sudo apt-get install -y libsodium-dev

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Adjust Version in gradle.properties by running Semantic Releas and exiting before publishing
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: ./.adjustVersion
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # Intentionally continue on error

      - name: Initialize submodule, generate .jar and .aar, and build (including tests)
        run: chmod +x initialize.sh && ./initialize.sh

      - name: Run Semantic Release again to publish the release, with the correct versions
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
